### ISSUE TITLE
Webp Image Compression?

### ISSUE THREAD

**Issue by tt2468** [Niek/obs-web#107]
I've found webp image compression to be more efficient on compression and use much less bandwidth. We've made sure we ship it with all OBS 28, and Ubuntu image-formats contains the codec too. iPhone used to be the only real browser limitation but as of like 2020 safari has support.

Thoughts?

**Comment by Niek** [comment]
Great idea, I have added support for this in bd57508. I'm doing a browser check as well as a OBS check - if both support webp, this is used for the screenshots.

By the way, it would be great if there was some kind of low-fps/low-res streaming support in obs-websocket. That would make things even more useful.

@all-contributors add @tt2468 for ideas
