### ISSUE TITLE
[Feature Request] Specify password in URL

### ISSUE THREAD

**Issue by richashford** [Niek/obs-web#145]
Enhanced bookmarking/deeplink by allowing password to be specified in URL perhaps using 2nd hash.

For example in App.svelte...

`
if (document.location.hash !== '') {
      // Read address from hash
      address = document.location.hash.slice(1)
      **password = document.location.hash.slice(2)**
      await connect()
    }
`

**Comment by Niek** [comment]
It's been suggested before, but I'm not in favor. It's a security risk since the password ends up in your browsing history.

**Comment by Niek** [comment]
Added now as a hidden option, for example:
http://obs-web.niek.tv/#ws://localhost:4455#password

**Comment by richashford** [comment]
Thanks @Niek - really appreciated - it will be a big help.

Totally respect the security risk too though - I guess important to clearly outline the risk and advise only to use in a InCognito or InPrivate browser window, never to use on a public device and ideally use only on a device with other forms or protection and only used by authorised users.
