### ISSUE TITLE
Ubuntu 22

### ISSUE THREAD

**Issue by kpdillon** [Niek/obs-web#193]
I am trying to build this on Ubuntu 22 LTS and it does not work.  Using a digital ocean droplet.  Any thoughts on how to make this work?

**Comment by Niek** [comment]
What doesn't work exactly? Can you share the error message?

**Comment by kpdillon** [comment]
Sorry, I should have included that.  Here it is... I donwnload the latest build and just run npm ci and this is what I get.  I get farther of I download the latest master code but I still can't get that to work either.

root@stream-2023:/home/obs-web-gh-pages# npm -v
8.5.1
root@stream-2023:/home/obs-web-gh-pages# npm ci
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-01T15_22_13_339Z-debug-0.log

**Comment by Niek** [comment]
That's because you downloaded the master ZIP of the pre-built website: https://github.com/Niek/obs-web/archive/gh-pages.zip

If you want to build the code yourself, download the ZIP of the source code instead: https://github.com/Niek/obs-web/archive/refs/heads/master.zip

**Comment by kpdillon** [comment]
Ok, but then I get this error on the second step when I run npm run dev

root@stream-2023:/home/obs-web-master# npm run dev

> svelte-app@1.0.0 dev
> rollup -c -w --bundleConfigAsCjs

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /home/obs-web-master/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.<anonymous> (/home/obs-web-master/node_modules/rollup/dist/bin/rollup:16:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/obs-web-master/node_modules/rollup/dist/bin/rollup' ]
}

**Comment by kpdillon** [comment]
ok, I appreciate your patience.  I think I updated to the latest and now I get this:

root@stream-2023:/home/obs-web-master# ls
Dockerfile  README.md     package-lock.json  public            src
LICENSE     node_modules  package.json       rollup.config.js
root@stream-2023:/home/obs-web-master# npm run dev
node:internal/modules/cjs/loader:1090
  const err = new Error(message);
              ^

Error: Cannot find module 'semver'
Require stack:
- /usr/share/nodejs/npm/lib/utils/unsupported.js
- /usr/share/nodejs/npm/lib/cli.js
- /usr/share/nodejs/npm/bin/npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/usr/share/nodejs/npm/lib/utils/unsupported.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/nodejs/npm/lib/utils/unsupported.js',
    '/usr/share/nodejs/npm/lib/cli.js',
    '/usr/share/nodejs/npm/bin/npm-cli.js'
  ]
}

Node.js v19.7.0
root@stream-2023:/home/obs-web-master#

**Comment by Niek** [comment]
Make sure to run `npm ci` first.

**Comment by kpdillon** [comment]
Whats weird is at the bottom it says node.js v19.7.0 but when I type node -v it still reports v12.22.9

**Comment by Niek** [comment]
Then your `npm` is using a different `node` version that your CLI, make sure your `$PATH` is correct - maybe restart your terminal.

**Comment by kpdillon** [comment]
ok - making progress.  I rebooted and I see v19.7.0.  Now when I run npm ci I get this... Seems to be dying.  Is my node version too new?

root@stream-2023:/home/obs-web-master# npm ci
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠧ reify:fsevents: sill reify mark deleted [ '/home/obs-web

Killed
root@stream-2023:/home/obs-web-master# 
root@stream-2023:/home/obs-web-master# 
root@stream-2023:/home/obs-web-master# 
root@stream-2023:/home/obs-web-master# 
root@stream-2023:/home/obs-web-master# npm ci
Killed####⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠧ reify:fsevents: sill reify mark deleted [ '/home/obs-web-master/node_modules/fsevents' ]

**Comment by Niek** [comment]
You have a messed up setup :) Try nuking `node_modules` and restarting. I can't really help you further with this as it's not related to obs-web.

**Comment by kpdillon** [comment]
Gotcha, OK - I'll build a new server from scratch and redo this.  I thought I did it yesterday but I'll work this out.  Thank you for your help.

**Comment by kpdillon** [comment]
I ended up getting it to build.  Thank you again for your help!  One question though.  On the main page it says download the latest build from here: https://github.com/Niek/obs-web/archive/gh-pages.zip.  You gave me the link https://github.com/Niek/obs-web/archive/refs/heads/master.zip.  

Should this be updated?

**Comment by Niek** [comment]
No, the ZIP is to the pre-built HTML, and you are looking for the latest source - those are two different things.

**Comment by kpdillon** [comment]
Ok, thanks.
