### ISSUE TITLE
Support for older browser ex. safari 9-10 ,IE11

### ISSUE THREAD

**Issue by coinraiser** [Niek/obs-web#23]
Any chance for that?
We have bunch of old ipads that we intend to use with obs web but can't cause safari showing blank page.
Maybe this can help? https://www.tutorialspoint.com/babeljs/index.htm

Thx in advance

**Comment by Niek** [comment]
I understand the reasoning, but unfortunately this is undoable. OBS-web was built on top of Svelte, and it doesn't support older browsers - nor is there a fork that supports such browsers. I'm closing this issue, but if anyone knows a quick solution I'm open to look into it.
