### ISSUE TITLE
Feature request: ability to specify host, port, and password for bookmarking

### ISSUE THREAD

**Issue by reedog117** [Niek/obs-web#30]
Hi! I was wondering if it would be possible to specify the host, port, and password in a URL so that navigating to it would automatically log me in to my OBS through the remote.

**Comment by Niek** [comment]
Specifying the host and port is actually supported, but maybe not so well documented 😄 When you connect, the URL changes to a form you can bookmark. For example: http://obs-web.niek.tv/#localhost:4444

The password is not in there on purpose, as this would be very insecure (it would be visible in your browsing history).
