### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by operandar** [Niek/obs-web#325]
Can anyone clarify if there's any kind of documentation for this project!?

**Comment by Niek** [comment]
What kind of documentation are you missing? Everything needed is mentioned in the readme.

**Comment by operandar** [comment]
I am trying to customise the UI somewhat.

The one issue I'm facing at the moment is trying to load Fontello fonts into the application. Do you know if this is possible?

**Comment by operandar** [comment]
This is now sorted. There was some issue with global.css not picking up Fontello specific css.

**Comment by operandar** [comment]
This is now sorted. There was some issue with global.css not picking up Fontello specific css.
