### ISSUE TITLE
Feature Request: change transition

### ISSUE THREAD

**Issue by iampaulmata** [Niek/obs-web#34]
I use a custom transition when going from/to my intro/outro scene to my live scene, but use the standard fade transition when live to switch between different scenes that have different camera views. I need to be able to select which transition I want to use before executing a scene change. According to the websocket documentation, it should be possible to show the available transitions in the web interface you made and allow that selection to be made - I use the "StreamControl" app on Android and that functionality exists but I want to use another desktop to do the remote controlling of OBS.

**Comment by Niek** [comment]
I started working on this a while ago, but I didn't finish. Will check soon if I can find some time to finish it.

**Comment by filiphanes** [comment]
can this issue be closed after merging #91 ?

**Comment by Niek** [comment]
Thanks, I skipped over this - closing now @filiphanes
