### ISSUE TITLE
Screen share functionality 

### ISSUE THREAD

**Issue by nickkostov** [Niek/obs-web#39]
Hello there,

I have found out today that the web-interface ( the share screen functionality is not working ).

I am applying a screenshot to it my friend:

![image](https://user-images.githubusercontent.com/35745114/102329412-09abe480-3f91-11eb-960b-f3cf1cd20354.png)

Thanks in advance for your advisory.

**Comment by Niek** [comment]
I have not experienced this so far... Can you share some more details about the browser you're using? Did you check the developer tools console for any error messages?

**Comment by nickkostov** [comment]
It is a chrome on Ubuntu

**Comment by Niek** [comment]
Check you check if you see any errors in the developer console?

**Comment by nickkostov** [comment]
Just to clarify, the option is in inspect element, I am no npm coder?

**Comment by Niek** [comment]
Yeah, when you see this behavior, just hit `Shift + Ctrl + J` - can you post the messages you see in the console?

**Comment by nickkostov** [comment]
Thank you, I will update you as soon as possible.
By the way is this all the code inside your repo or you pull it from somewhere else, I am interested into looking how exactly it works, so I can improve the engine.

**Comment by nickkostov** [comment]
![Uploading image.png…]()

**Comment by lucaspontoexe** [comment]
I'm getting the same error. From the console log: 
`bundle-v232f602.js:3 Error sending command TakeSourceScreenshot  - error is: {error: "unsupported picture format: jpeg", message-id: "41", status: "error", messageId: "41"}`

**Comment by lucaspontoexe** [comment]
I tried with `png` and it worked

**Comment by nickkostov** [comment]
I just realizedmy screenshot did not upload, sorry about that one

**Comment by kewickviper** [comment]
Getting the exact same error as lucas, changing to png in the developer console didn't resolve for me.

**Comment by lucaspontoexe** [comment]
> Getting the exact same error as lucas, changing to png in the developer console didn't resolve for me.

Check your console and see if the format really changed. Because of the service worker, the code is not updated right away.
You can try again in an incognito window

**Comment by Niek** [comment]
I just pushed a new version at http://obs-web.niek.tv/ that uses `jpg` instead of `jpeg`... apparently some platforms don't support the 4-letter format. Can you please check @lucaspontoexe @kewickviper @nickkostov?

**Comment by nickkostov** [comment]
I will attempt it ASAP and will update you shortly

**Comment by kewickviper** [comment]
@Niek doesn't work for me same error message but with 'jpg': 

Error sending command TakeSourceScreenshot  - error is: {error: "unsupported picture format: jpg", message-id: "30", status: "error", messageId: "30"}

Using Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by Niek** [comment]
Are you all running OBS on Linux? Seems like the obs-websocket build is missing JPG support, which is very strange.

**Comment by Niek** [comment]
Found the relevant issue: https://github.com/Palakis/obs-websocket/issues/634

A quick workaround is to install the `qt5-image-formats-plugins` package.

**Comment by tt2468** [comment]
@Niek That is only for Ubuntu, and the dependency on the package has not changed with any OBS version. The correct Qt image format binaries must be included in the OBS release files for windows, which we do not have at the moment.

**Comment by kewickviper** [comment]
@Niek Am running everything on windows including OBS

**Comment by Niek** [comment]
I switched the screenshot format to PNG until there's a fix.

**Comment by nickkostov** [comment]
I have just regarded the trouble if it is still reoccurring, I have some positive news. It seems alright.
I think you can close this issue and not to bother anymore with it.
By the way I am using it on Chrome in Ubuntu 20.04 which is always in incognito.
