### ISSUE TITLE
show errors? 

### ISSUE THREAD

**Issue by rszyma** [Niek/obs-web#390]
obs-web doesn't show any errors when it fails to connect to websocket, it makes it unnecesserily hard to debug non-working setup. Please add error logging!

**Comment by Niek** [comment]
<img width="259" alt="Screenshot 2024-07-01 at 10 16 05" src="https://github.com/Niek/obs-web/assets/213140/d9abca52-0217-45f4-8b8a-2dbffd3a8235">
The error message is (should be) shown in the disconnect button> If you want more details, you can also check the developer console.

**Comment by rszyma** [comment]
Sorry I should have mentioned that I had these problems on mobile, and there's no developer console there. When entering url, password and clicking "Connect" button, the website just flashes (refreshes) and no error is shown. This is very user unfriendly, and I'm even wondering is the connect button even works in the first place.

**Comment by Kupie** [comment]
I'm getting the same issues, I'll try and use remote debugger for Firefox/Chrome today once I'm at home at my PC to see why it won't work on mobile with ngrok forwarding (works with both chrome/firefox desktop browsers on my PC)

**Comment by joeskeen** [comment]
It would be great if you loaded Eruda if you add the query string parameter "eruda=true". I've used this on some PWAs I've built, and been able to pull up dev tools, even on a smart fridge!

https://eruda.liriliri.io
