### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by dinther** [Niek/obs-web#42]
I have a use case where I want the remote user to be able to switch scene but not control the stream or record.
In fact in some cases not even have the image pre-view.

It would be awesome if there was a place in the code like a json file where a bunch of parameters were kept to toggle certain functionality on and off.

**Comment by Niek** [comment]
Hi Dinther,

Such as request would be better suited towards the [obs-websocket](https://github.com/Palakis/obs-websocket) project. This project (obs-web) is simply a web interface on top of the websocket plugin. Even if we would hide specific information, it'd still be accessible through the same websocket, so insecure.

I recommend opening a feature request issue over there, closing this issue now.
