### ISSUE TITLE
Request: sources? 

### ISSUE THREAD

**Issue by awrebels** [Niek/obs-web#43]
I'm trying to figure out a way to remotely control a source. Ideally the webpage would only have one button. The source would be in a nested scene so not necessarily a source in the active scene. From what I've seen with the web integrations of obswebsockets it only pulls the active scene. 

Is this doable?

**Comment by Niek** [comment]
Thanks for raising this report. I tried to understand what you're requesting but it's not clear to me. What do you mean with 1 button and the source in a nested scene? Can you maybe draw a mockup to show what you're looking for?

**Comment by awrebels** [comment]
Sorry for not being clearer; and it's likely very specific to my use case. Basically i would have a webpage with an html button for instance 
![button](https://user-images.githubusercontent.com/28576527/107601935-15650180-6bf6-11eb-93b4-677154b8d708.png)
Onclick it would trigger a source(s) visibility to on/show. Ideally it would also delay a couple seconds, and shut the source off automatically. 

When I say nested scene i mean the following. Take for instance SOURCE_to_be_toggled is within Scene 1 and then Scene 1 is in Scene 2. Scene 2 is the active scene. I would want to be able to trigger the SOURCE in Scene 1 while Scene 2 is active. 
Scene 1 > SOURCE_to_be_toggled
Scene 2 > Scene 1
 
i'd very much appreciate if you can give me some insight or point me in the right direction. I've been trying to figure out a solution for this for a while and your app seems like it is getting closer to the solution :)

**Comment by Niek** [comment]
At the moment we don't show sources at all - if I'm understanding you correctly you'd like to see the sources in the scenes with the ability to toggle them on and off, correct? That's perfectly doable, but I'm not sure if that's possible while keeping the UI minimal. Maybe in a modal box? But that would make it harder to quickly toggle something on and off.

**Comment by awrebels** [comment]
Ideally this would be a standalone page lets say http://URL.COM/obs-web/sourceselector/1 on this page you could either select or have preselected the set of sources that you want to trigger on and off. Like a panel of buttons.

![image](https://user-images.githubusercontent.com/28576527/107794014-ec8f5a00-6d24-11eb-800c-57a0a0de789b.png)

That way instead of cluttering what exists already it is a separate page. 

(and i don't know if this little project interests you but I would love to discuss hiring you for the time invested or if you know someone knowledgable)

thanks

**Comment by Niek** [comment]
That would be doable in a modal box. It's a bit out of scope for this project, but I can work on it if you're willing to sponsor it - see https://github.com/sponsors/Niek

**Comment by awrebels** [comment]
Deal. Let me know if you have further questions regarding the above. There’s also some features that would be nice to have with this new modal box thing. For instance if it could auto connect to the websocket on page load i.e. rather than requiring the user to enter the address.

**Comment by BBSDCA** [comment]
modal would be great except would that work on a android or iphone?  I need such a button too and use it from mobile.

that all being said, I'm ok putting the buttons down at the bottom so I can just scroll down and have that part of the page available to me.

THANK YOU!!!

**Comment by filiphanes** [comment]
@awrebels check out latest version.
When you name your scene `Scene 1 (switch)` and then put it as source in `Scene 2`, you can switch visibility of all sources in `Scene 1 (switch)`.
You could use it to show specific Source when it ends with with transparency.

I have implemented this for switching between many looping background by visually seeing thumbnails.
