### ISSUE TITLE
Audio Bar on OBS Web

### ISSUE THREAD

**Issue by dimastrihandika** [Niek/obs-web#436]
Hi, is that possible to get the audio bar/visualizer in obs web? 
![Screenshot_2024-10-31-01-17-30-19_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/user-attachments/assets/623e0b2e-81af-4934-b3f9-7a263abe3dc4)

**Comment by Niek** [comment]
No, as far as I'm aware there is no event for this: https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#events
