### ISSUE TITLE
Not an issue, but is it possible to send / receive custom variable through the websocket?

### ISSUE THREAD

**Issue by Marcuzzz** [Niek/obs-web#59]
I added a Random Scene button and functions (see below).
I want to schedule a livestream and want to start the Random Scene automatically on the OBS Server. 
Not sure yet how I'm going to do that but I think I can figure that out.

The idea is that the livestream is going to start automatically and someone else can then (if they want) take over (on a tablet for example) and switch off the Random Scene function. But to do that I think I need to be able to send / receive custom variables through the websocket to tell if "Random Scene" is turned on and to tell it to stop the Random Scene function.. 

Any idea if this is possible?

Random Scene button implementation:
```
var statusrandom = false;

 async function RandomScene() {

  if (!statusrandom) {
    console.log('start randomscene' + SetRandom);    
    statusrandom = true;
    StartRandomScene()

  } else {
    console.log('stop randomscene' + SetRandom);
    statusrandom = false;
  }

  }


  async function StartRandomScene() {

    while (true) {

    if (statusrandom) {

    timeoutrandom = (Math.floor(Math.random() * 4) + 10) * 1000;
    console.log('delay set',timeoutrandom);
    await delay(timeoutrandom);
    console.log('delay finished',timeoutrandom);
    GetRandomScene();

    } else {

    break;

    }

    }

  }


  async function GetRandomScene() {
    previousrandom = Math.floor(Math.random() * 4) + 1;
    //await sendCommand('SetCurrentScene', { 'scene-name': 'Cam' + previousrandom });

    await sendCommand('SetPreviewScene', { 'scene-name': 'Cam' + previousrandom });
    await sendCommand('TransitionToProgram');

    console.log('Scene changed!!');

  }
```

and the button:

```
            {#if statusrandom}
            <a class="button is-danger is-light" on:click={RandomScene}>Stop Random Scene</a>
            {:else}
            <a class="button is-danger is-light" on:click={RandomScene}>Random Scene</a>
            {/if}
```

**Comment by Niek** [comment]
Hi, if you want to send a custom command through the websocket, please see the https://github.com/Palakis/obs-websocket project. There's also an active discord here: https://discord.gg/jRwztBEW
