### ISSUE TITLE
password

### ISSUE THREAD

**Issue by crazy4groovy** [Niek/obs-web#7]
How do I specify a password to connect remotely?

**Comment by Niek** [comment]
Just connect, and OBS-web will ask you for the password. Let me know if you encounter any issues.

**Comment by crazy4groovy** [comment]
![image](https://user-images.githubusercontent.com/1110812/85589529-a3618d00-b611-11ea-96f1-381a7a3a8047.png)

![image](https://user-images.githubusercontent.com/1110812/85589611-b2e0d600-b611-11ea-88f3-3255b9e3d3b2.png)

When I try to connect to `wss://fac870dddaae.ngrok.io`, just getting an `Connection error.` message.

(This post should be OK for security, I have password protection)

**Comment by crazy4groovy** [comment]
Oh, I just leave off the `wss://` part and it works, I see the password prompt!

`fac870dddaae.ngrok.io`

thanks!

**Comment by Niek** [comment]
It's a good usability point though, the UI should handle such hosts. I have fixed it in https://github.com/Niek/obs-web/commit/05a27937a721109e1ca47c80a70c7d0c3b2a2f6b

**Comment by Niek** [comment]
@all-contributors please add @crazy4groovy for bug reports
