### ISSUE TITLE
Make password entry non-modal

### ISSUE THREAD

**Issue by rmoriz** [Niek/obs-web#71]
Current implementation as a modal entry is not supported by almost all password managers eg 1password. As each reload triggers the input of the password, this is not only a usability issue but will also make people use weak passwords.

**Comment by Niek** [comment]
The prompt is not ideal for sure - I'll check how this can be replaced with a regular Bulma modal with a password input field. That should fix the issues.

**Comment by Niek** [comment]
This was fixed by @filiphanes in PR #91 - see http://obs-web.niek.tv/ now
