### ISSUE TITLE
Button refresh input

### ISSUE THREAD

**Issue by Saexy** [Niek/obs-web#74]
Hello, can you add a button that refresh a input? i really need this

**Comment by Saexy** [comment]
i thing you can use PressInputPropertiesButton

**Comment by Niek** [comment]
You can simply refresh the page.

**Comment by Saexy** [comment]
but, if i refresh the page refresh all the inputs?

**Comment by Saexy** [comment]
i need a button that refreshes a browser input

**Comment by Niek** [comment]
You mean a browser source? What do you want to refresh, the page shown in the browser source? That is not possible AFAIK.

**Comment by Saexy** [comment]
is it not possible to have a request that presses the source refresh button?

**Comment by Niek** [comment]
I see there is this function: https://github.com/obsproject/obs-websocket/blob/4.x-compat/docs/generated/protocol.md#refreshbrowsersource

However, I won't implement this as currently obs-web doesn't deal with sources at all - only scenes. Sources are planned in the future, after which I can revisit this idea.
