### ISSUE TITLE
OBS-websocket 5.0.0 support

### ISSUE THREAD

**Issue by alessionossa** [Niek/obs-web#76]
Although I have not looked at code and documentation, I think the project needs some adjustments to be compatible with [OBS-websocket](https://github.com/obsproject/obs-websocket) 5.0.0 that will be released soon.

**Comment by Niek** [comment]
Absolutely. I'm in touch with the OBS-websocket authors, once v5 drops I will update the code.

**Comment by alessionossa** [comment]
Just to update the thread: [5.0.0 beta1 has been released](https://github.com/obsproject/obs-websocket/releases/tag/5.0.0-beta1) and it’s almost feature-complete.

**Comment by Niek** [comment]
Both [OBS-websocket 5.0.0](https://github.com/obsproject/obs-websocket/releases/tag/5.0.0) and [OBS-websocket-js 5.0.0](https://github.com/obs-websocket-community-projects/obs-websocket-js/releases/tag/v5.0.0) are released, so I'll work on a separate OBS-web v5 branch. Ideally we should have two versions hosted (/v4 and /v5) so users can use the appropriate frontend.

**Comment by Bartyx** [comment]
Hello. Any news about v5 version of your app?

**Comment by Niek** [comment]
I have a working v5 branch: https://github.com/Niek/obs-web/tree/obs-websocket-5

Just need to figure out a way to keep hosting the v4 version for those who don't want to upgrade (yet)...

**Comment by Niek** [comment]
Finished now, see http://obs-web.niek.tv/
Archived v4 version is available at: http://obs-web.niek.tv/v4/

**Comment by Niek** [comment]
@all-contributors add @alessionossa for ideas
